### PR TITLE
Review

### PR DESCRIPTION
**Pull request by anattoly**

### CODE REVIEW

**Review by dd994 — APPROVED** [review]
I have no comments, well done

**Comment by i-kovalyshyn** [comment]
Hi, as for me, good code, well done!

**Review by NickRbk — APPROVED** [review]
Notes:
1) if you repeat some string multiple times it is better to define it as constant
2) delete all unused methods
3) don't use underscore in package name (its Python style, not Java convention).

In overall, the task is done!

**Comment by anattoly** [comment]
> Notes:
> 
> 1. if you repeat some string multiple times it is better to define it as constant
> 2. delete all unused methods
> 3. don't use underscore in package name (its Python style, not Java convention).
> 
> In overall, the task is done!

Done all remarks

**Pull request closed without merging**
